[FEAT] 로그인 뷰
team-MUMENT/MUMENT-iOS pull request #152
Opened 2022-11-01 11:46 UTC by jimin-kiim

## 🎸 작업한 내용
- 배경사진, 로고이미지, 버튼, 레이블 올리기
- 레이블 내에서 부분 스트링 스타일 변화 주기
- 레이블 내에서 부분 스트링 링크 걸기

## 🎶 PR Point
- `배경사진, 로고이미지, 버튼, 레이블 올리기`
  - 배경 사진이 단색이 아니라 패턴이 있어서 content mode는 aspect fit으로 했습니다
  - 버튼 색깔을 따로 지정 + 이미지 넣기 + 간격 조정을 하기보다는 하나의 이미지로 바로 쓰는 게 나을 것 같아 후자 방법으로 했습니다
- `레이블 내에서 부분 스트링 스타일 변화 주기` 
  - 정빈 언니가 정성스럽게 넣어준 UILabel+ 의 setColor 메소드를 변형하여 setHyperlinkedStyle 메소드를 작성했습니다. 한 label 내에서 여러 부분에 적용시키고 싶은 경우라 스타일을 적용할 부분을 배열로 받도록 했습니다. 
- `레이블 내에서 부분 스트링 링크 걸기` 
  - 버튼이 아니라 레이블이기에 tapRecognizer로 탭을 인식해 이벤트 처리해야하고, 이에 필요한 boundingRectForCharacterRange 메소드를 UILabel+에 추가하였습니다. `'개인정보처리방침' 부분`에 적용할 땐 문제가 없지만 `'이용약관' 부분`에 적용할 땐 오차가 있어 하드코딩으로 조정해주었습니다. (SE, 14 pro 기준 기기대응 잘 됩니다)
  - 링크를 여는 방법이 다양한데(앱 밖을 나가 사파리 열기, 웹뷰를 이용해서 뷰로 추가되게 하기 등) 클릭 시 링크가 앱 내에서 열리도록 하는 게 가장 자연스러운 것 같아 SafariServices 를 import 하고 SFSafariViewController를 사용해 구현했습니다. 
  - 링크는 아직 공지가 안된 것 같아서 '이용약관' 클릭 시엔 구글이, '개인정보처리방침' 클릭 시엔 깃허브가 열리도록 했습니다. 
- 로그인 기능 구현은 아직 안했고 버튼 클릭 시 print문만 출력되도록 세팅해두었습니다.
- SignInVC에 final, private 키워드를 챙겨 붙여보았습니다

## 📸 스크린샷
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-01 at 20 38 03](https://user-images.githubusercontent.com/25932970/199224692-ce7b0ad1-ca47-429e-b9a5-5c9d61a898f3.gif)

## 💽 관련 이슈
- Resolved: #142

2022-11-01 15:14 UTC, dev-madilyn requested changes
확인했어요~ 컨벤션 관련 리뷰만 확인해서 반영 부탁!!

2022-11-01 15:14 UTC, dev-madilyn commented on MUMENT/MUMENT/Global/Extensions/UILabel+.swift
> +    func setHyperlinkedStyle(to targetStrings: [String], with font: UIFont
잘쓸게용~~~ 굿

2022-11-01 15:14 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
> +        $0.setHyperlinkedStyle(to: ["이용약관","개인정보처리방침"],with:.mumentB7B12)
`$0.setHyperlinkedStyle(to: ["이용약관", "개인정보처리방침"], with: .mumentB7B12)`
요렇게 수정해 주세용 띄어쓰기!!

2022-11-01 15:14 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
> +                present(url:  "https://www.google.com")
요기는 `url:` 뒤에 공백이 두 개 들어 있는 것 같아요~~

2022-11-01 15:14 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
> +            let actualTermsRect = CGRect(x: calaulatedTermsRect.origin.x + 40, y: calaulatedTermsRect.origin.y, width: calaulatedTermsRect.width - 10, height: calaulatedTermsRect.height)
이 정도는 하드코딩도 아닌 것 같애... 지민이 똑똑하당 ...

2022-11-01 16:36 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
> +                present(url:  "https://www.google.com")
역시 클라 참개발자는 눈썰미가 다르네용👍🏻 띄어쓰기 두 부분 수정 후 푸시 완료했습니다!!

2022-11-01 17:02 UTC, dev-madilyn approved these changes
확인이요!! 👍

2022-11-02 09:58 UTC, daminoworld approved these changes
boundingRectForCharacterRange 코드에 처음 보는 메서드들이 많아서 바로 이해하기는 좀 어렵네요ㅎ 지금처럼 URL 적용할때 뿐만 아니라 다양하게 써먹을 수 있을 것 같아서 시간 될 때 공부좀 해봐야겠습니다! 
갓기 지미니 수고하셨습니다!🔥

2022-11-02 09:58 UTC, daminoworld commented on MUMENT/MUMENT/Global/Extensions/UILabel+.swift
> +    func boundingRectForCharacterRange(subText: String) -> CGRect? {
처음보는 NS 메서스들이 있어서 좀 어렵네요ㅎ

2022-11-02 09:58 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/SignIn/SignInVC.swift
> +            let actualTermsRect = CGRect(x: calaulatedTermsRect.origin.x + 40, y: calaulatedTermsRect.origin.y, width: calaulatedTermsRect.width - 10, height: calaulatedTermsRect.height)
오 이렇게 영점 조절을ㅎㅎ 짱이에요~

2022-11-02 10:13 UTC, jimin-kiim commented on MUMENT/MUMENT/Global/Extensions/UILabel+.swift
> +    func boundingRectForCharacterRange(subText: String) -> CGRect? {
관련 코드들을 많이 접하고 익숙해지시다보면 괜찮아지실 겁니당ㅎㅎ

2022-11-02 10:14 UTC, merged