[FEAT] 홈 뷰 상단 바 구현
team-MUMENT/MUMENT-iOS pull request #26
Opened 2022-07-10 03:07 UTC by jimin-kiim

## 🎸 작업한 내용
- 테이블 뷰 세팅
- 홈 뷰 상단 바
- 현재는 검색창이 테이블 뷰 섹션에 포함시켜 두었지만 이후 상단 바로 옮겨 스크롤 시 픽스되는 영역으로 추가할 계획입니다.
지금까지 작성한 코드의 양이 벌써 꽤 많아 현재 작업한 부분까지 PR 요청 보냅니다.

## 🎶 PR Point

사소한 부분이라도 피드백 주시면 감사하겠습니다😃

- TableView Header로 만들어 보려 했으나 독립적인 UIView로 만드는 게 더 편해 후자로 구현했습니다.
- 테이블 뷰 섹션에 들어갈 뷰들은 TVC로 명명했는데, 헤더는 어떻게 해야 할까 고민하다가 TVHeader로 네이밍했습니다. 

## 📸 스크린샷
![Simulator Screen Recording - iPhone 13 mini - 2022-07-10 at 11 48 41](https://user-images.githubusercontent.com/25932970/178129658-8ed8e41d-8aa3-4e76-8793-f00bb32460c8.gif)

## 💽 관련 이슈
- Resolved: #11

2022-07-10 03:40 UTC, dev-madilyn requested changes
`SceneDelegate` 파일이랑, 제약조건 관련 부분은 수정해 주시구요~~~
나머지는 코멘트 확인 한 번만 해 주시면 감사 🙆🏻‍♀️ 수고해써 짐니 ~~~!!!!!!!!!!!!!!!

2022-07-10 03:40 UTC, dev-madilyn commented on MUMENT/MUMENT/Application/SceneDelegate.swift
요부분 테스트하려고 HomeVC로 바꾼 거 맞나요~? MumentTabBarController로 다시 바꿔 주세요~~!~!~!~!

2022-07-10 03:40 UTC, dev-madilyn commented on MUMENT/MUMENT/Global/Protocols/Reusable.swift
> +}
아~~ 내가 이거 안 넣었던 이유가(노션에서 봤는데)
지금 모든 클래스에서 `.className` 하면 해당 클래스 이름이 string으로 반환되거든 !! (`HomeVC.className` 등)
혹시 className 이외에 따로 Reusable을 사용해야 하는 경우가 있을까요~??

2022-07-10 03:40 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/Home/MumentForTodayTVC.swift
> +        $0.font = .systemFont(ofSize: 16)
요기 들어간 폰트나 컬러 이런 건 다 나중에 바꾸는 건가여?

2022-07-10 03:40 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +            $0.height.equalTo(30)
요기 `.adjusted` 적용해 주면 좋을 것 같아요~~~~~ 헤더 자체가 `HomeVC`에서 제약조건 걸 때에는 adjusted 적용이 되어 있는데, 그 안에 들어가는 요소가 adjusted 적용이 안 되어 있으면 헤더뷰는 기기대응이 되는데 그 안에 있는 요소들 기기대응이 안 될 것 같슴다!

2022-07-10 03:40 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +    lazy var logoButton = UIButton().then{
로고를 `UIImageView`가 아닌 `UIButton`으로 넣은 이유가 있ㅇ르까요~?

2022-07-10 03:52 UTC, jimin-kiim commented on MUMENT/MUMENT/Application/SceneDelegate.swift
네 맞습니다! 제가 깜빡 잊었네요 감사합니다 ! 변경 완료했습니다 😄

2022-07-10 03:52 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/MumentForTodayTVC.swift
> +        $0.font = .systemFont(ofSize: 16)
네 맞습니다, 테이블 뷰 셀로 맞게 들어오는지 확인하기 위해 임의로 넣어둔 부분입니다!

2022-07-10 03:57 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +            $0.height.equalTo(30)
이해됐습니다 감사합니다 ! 이와 관련해서 추가로 궁금한 부분이 생겼는데요, 기기대응을 위해 모든 제약조건 설정에 `.adjusted`, `.adjustedH`를 적용해 주는 게 좋은가요?

2022-07-10 03:59 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +    lazy var logoButton = UIButton().then{
버튼 역할을 하는 부분일지 아닐지 확실치 않아 일단 버튼으로 구현한 뒤 푸시했습니다! `UIImageView`로 변경하는 게 나을까요? 😃

2022-07-10 04:01 UTC, dev-madilyn commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +            $0.height.equalTo(30)
@jimin-kiim 음 "모든" 이라고 완전 단정지을 수는 없을 것 같은데!
width 100짜리 폰에서 width 10짜리 뷰를,
width 200짜리 폰에서 width 20으로 보이게 하고 싶다면 adjusted를 적용해야 하구, width 10으로 보이게 하고 싶다면 안 하는 게 맞아요!

약간 오토레이아웃 짤 때도 superView 대비 배수(muliple인가 어쩌구)로 넣느냐, 걍 width/height 때려박느냐 그 차이인데...
이거는 지민이의 의도에 따라 달라질 것 같아요~!!!

2022-07-10 04:02 UTC, dev-madilyn approved these changes
수정사항 확인했어요~ 굿굿

2022-07-10 04:02 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +    lazy var logoButton = UIButton().then{
넵 감사합니다! 😃

2022-07-10 04:10 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +            $0.height.equalTo(30)
친절한 설명 정말 감사합니다! 이해됐습니다! 헤더 안의 뷰 제약조건 설정에 적용 완료하였습니다!😄

2022-07-10 11:15 UTC, daminoworld approved these changes
기강지민...저희 같은 YB 맞죠?ㅠ 덕분에 기강 제대로 잡혀버렸습니다! 수고하셨습니다!

2022-07-10 11:15 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
> +    }
각 섹션마다 같은 리턴값 1을 가지니까 `case 0...4: return 1` 이런식으로 코드를 줄일 수 있을 것 같습니다!
[<참고> swift switch case](https://nightohl.tistory.com/entry/Swift-%EA%B8%B0%EC%B4%88-switch-case-%EB%AC%B8)

2022-07-10 11:15 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
> +            cellHeight = 300.adjustedH
여기도 위에 처럼 `case 1...4 : ~` 이런 식으로 적용 가능 할 것 같습니다!

2022-07-10 11:15 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +class TVHeader: UIView {
여기도 위와 마찬가지로 TVHeader 대신 좀 더 명시적인 이름이면 좋을것 같습니다~

2022-07-10 11:15 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/RecentMumentsTVC.swift
> +    }
이 코드는 어떤 역할을 하는지 궁금합니다!😭

2022-07-10 12:54 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +class TVHeader: UIView {
감사합니다! HomeTVHeader로 변경하면 괜찮을까요? 😃

2022-07-10 12:58 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
> +            cellHeight = 300.adjustedH
감사합니다! 반영 완료했습니다!😄

2022-07-10 12:58 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
> +    }
참고 링크까지 걸어주셨네요 감사합니다! 반영해 푸시 완료했습니다!😄

2022-07-10 12:59 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/HomeVC.swift
> +    private let headerView = TVHeader()
놓쳤던 부분 짚어주셔서 감사합니다! homeTV로 변경해 푸시 완료했습니다!😄

2022-07-10 13:00 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/TVHeader.swift
> +class TVHeader: UIView {
@jimin-kiim 좋은것 같습니다~!

2022-07-10 18:22 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/RecentMumentsTVC.swift
> +    }
코드베이스로 UIKit 프레임워크에 있는 클래스들(UIView, UITableViewCell 등)을 상속받아 새로운 커스텀 클래스를 만들 때는 두 개의 생성자 메소드를 오버라이딩해 작성해 줘야 합니다. 해당 커스텀 클래스를 ` 1. 코드 상에서 사용할 때 필요한 생성자`와 `2. 스토리보드에서 호출하여 사용할 때 필요한 생성자`인데요, 

위 코드는 전자에 속합니다. 
UIView를 상속할 때 :  override init(frame: CGRect)
UITableViewCell : override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) ->바로 위 코드입니다!
코드베이스로 구현하는 과정에서 커스텀 클래스의 인스턴스를 생성할 때 setLayout함수를 호출해 해당 함수 안에서 작성한 대로 UI들을 올려 초기화해주는 역할을 합니다.

2022-07-10 18:37 UTC, jimin-kiim commented on MUMENT/MUMENT/Sources/Scenes/Home/CarouselTVC.swift
> +        fatalError("init(coder:) has not been implemented")
후자인 `2. 스토리보드에서 호출하여 사용할 때 필요한 생성자`입니다. 

`명확한 이해를 위해서는 Interface Builder, Archiving, UnArchiving, NSCoding 프로토콜을 키워드로 공부해야 하는 것 같습니다!ㅠ` 제가 이해한 선 안에서 겉으로라도 코드를 읽을 수 있는 설명을 덧붙여보자면

부모 클래스에서 자식 클래스도 꼭 재정의하라!라고 지정했기에 override 키워드 자리에 required가 붙은 형태이고 필수적으로 써줘야 할 코드이기에 이를 쓰지 않으면 Xcode에서 자동으로 경고를 보여주며 해당 메소드를 추가하라고 합니다. 그때 추가하기 버튼을 누르면 자동으로 완성되는 코드가 바로 위 코드입니다. 

fatalError는 해당 생성자를 접근할 때 런타임 에러가 나도록 하는 코드이고 @available은 같은 역할을 런타임이 아니라 컴파일 타임에서 수행되게 하는 표현으로 xib, 스토리보드는 사용하지 않고 코드베이스로만 구현할 것인데 이를 접근하면 에러가 발생하도록 하기 위한 목적으로 쓰인다고 합니다. 

@available은 괄호 안의 조건에 따라 해당 코드 블럭을 수행할 것인지 말 것인지 결정해주는 표현인데 괄호 속 표현이 `*, unavailable`이기에 모든 플랫폼에서 이 코드를 수행하지 않게 하라!라는 뜻이라고 합니다. 여기서는 난 xib, 스토리보드는 사용하지 않고 코드베이스로만 구현할 것인데 xib, 스토리보드에서 호출하여 사용할 때 필요한 이 생성자를 접근하면 컴파일 에러를 내!라는 뜻인 것 같습니다.

2022-07-10 18:41 UTC, merged

2022-07-11 07:15 UTC, daminoworld commented on MUMENT/MUMENT/Sources/Scenes/Home/RecentMumentsTVC.swift
> +    }
친절한 설명 너무 감사합니다!!